// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe-lm9KA38L7Ho7udTxkEqR_g4t3jrBds',
    appId: '1:352397713763:web:a219d66d7f10f7bcd73356',
    messagingSenderId: '352397713763',
    projectId: 'instagramclone-7a30c',
    authDomain: 'instagramclone-7a30c.firebaseapp.com',
    storageBucket: 'instagramclone-7a30c.firebasestorage.app',
    measurementId: 'G-NK9CG677ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcjcK7L7anz7qTJD7ekGR0srn79bEWZxg',
    appId: '1:352397713763:android:23c9f16abd450c42d73356',
    messagingSenderId: '352397713763',
    projectId: 'instagramclone-7a30c',
    storageBucket: 'instagramclone-7a30c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD__sg48lY4O3ynT1VFJnlzi5ZHctorVE',
    appId: '1:352397713763:ios:72b848169665e9d0d73356',
    messagingSenderId: '352397713763',
    projectId: 'instagramclone-7a30c',
    storageBucket: 'instagramclone-7a30c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD__sg48lY4O3ynT1VFJnlzi5ZHctorVE',
    appId: '1:352397713763:ios:72b848169665e9d0d73356',
    messagingSenderId: '352397713763',
    projectId: 'instagramclone-7a30c',
    storageBucket: 'instagramclone-7a30c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe-lm9KA38L7Ho7udTxkEqR_g4t3jrBds',
    appId: '1:352397713763:web:7994bd45b657b692d73356',
    messagingSenderId: '352397713763',
    projectId: 'instagramclone-7a30c',
    authDomain: 'instagramclone-7a30c.firebaseapp.com',
    storageBucket: 'instagramclone-7a30c.firebasestorage.app',
    measurementId: 'G-ZJ6REW5X87',
  );
}
